name: condominioapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  meta: ^1.7.0
  http: ^0.13.4
  provider: ^6.0.3
  equatable: ^2.0.3
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  test: ^1.21.1
  mockito: ^5.2.0
  faker: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/ui/assets/

